export const FRIEND_REQUEST_RECIEVED = "FRIEND_REQUEST_RECIEVED";
export const FRIEND_REQUEST_RECIEVED_RESET = "FRIEND_REQUEST_RECIEVED_RESET";
export const FRIEND_REQUEST_RECIEVED_ERROR = "FRIEND_REQUEST_RECIEVED_ERROR";
export const FRIEND_REQUEST_RECIEVED_LOADING =
  "FRIEND_REQUEST_RECIEVED_LOADING";

export const ACCEPT_REQUEST = "ACCEPT_REQUEST";
export const ACCEPT_REQUEST_RESET = "ACCEPT_REQUEST_RESET";
export const ACCEPT_REQUEST_ERROR = "ACCEPT_REQUEST_ERROR";
export const ACCEPT_REQUEST_LOADING = "ACCEPT_REQUEST_LOADING";

export const REJECT_REQUEST = "REJECT_REQUEST";
export const REJECT_REQUEST_RESET = "REJECT_REQUEST_RESET";
export const REJECT_REQUEST_ERROR = "REJECT_REQUEST_ERROR";
export const REJECT_REQUEST_LOADING = "REJECT_REQUEST_LOADING";

export const SEND_REQUEST = "SEND_REQUEST";
export const SEND_REQUEST_RESET = "SEND_REQUEST_RESET";
export const SEND_REQUEST_ERROR = "SEND_REQUEST_ERROR";
export const SEND_REQUEST_LOADING = "SEND_REQUEST_LOADING";

export const SEARCH_FRIENDS = "SEARCH_FRIENDS";
export const SEARCH_FRIENDS_RESET = "SEARCH_FRIENDS_RESET";
export const SEARCH_FRIENDS_ERROR = "SEARCH_FRIENDS_ERROR";
export const SEARCH_FRIENDS_LOADING = "SEARCH_FRIENDS_LOADING";
