export const ADD_GROUP = "ADD_GROUP";
export const ADD_GROUP_ERROR = "ADD_GROUP_ERROR";
export const ADD_GROUP_LOADING = "ADD_GROUP_LOADING";
export const ADD_GROUP_RESET = "ADD_GROUP_RESET";

export const PROCESS_GROUP_REQUEST = "PROCESS_GROUP_REQUEST";
export const PROCESS_GROUP_REQUEST_ERROR = "PROCESS_GROUP_REQUEST_ERROR";
export const PROCESS_GROUP_REQUEST_LOADING = "PROCESS_GROUP_REQUEST_LOADING";
export const PROCESS_GROUP_REQUEST_RESET = "PROCESS_GROUP_REQUEST_RESET";

export const REMOVE_FRIEND = "REMOVE_FRIEND";
export const REMOVE_FRIEND_ERROR = "REMOVE_FRIEND_ERROR";
export const REMOVE_FRIEND_LOADING = "REMOVE_FRIEND_LOADING";
export const REMOVE_FRIEND_RESET = "REMOVE_FRIEND_RESET";

export const ADD_MEMBERS = "ADD_MEMBERS";
export const ADD_MEMBERS_ERROR = "ADD_MEMBERS_ERROR";
export const ADD_MEMBERS_LOADING = "ADD_MEMBERS_LOADING";
export const ADD_MEMBERS_RESET = "ADD_MEMBERS_RESET";

export const DELETE_GROUP = "DELETE_GROUP";
export const DELETE_GROUP_ERROR = "DELETE_GROUP_ERROR";
export const DELETE_GROUP_LOADING = "DELETE_GROUP_LOADING";
export const DELETE_GROUP_RESET = "DELETE_GROUP_RESET";

export const UPDATE_GROUP = "UPDATE_GROUP";
export const UPDATE_GROUP_ERROR = "UPDATE_GROUP_ERROR";
export const UPDATE_GROUP_LOADING = "UPDATE_GROUP_LOADING";
export const UPDATE_GROUP_RESET = "UPDATE_GROUP_RESET";

export const CHANGE_GROUP_VISIBILITY = "CHANGE_GROUP_VISIBILITY";
export const CHANGE_GROUP_VISIBILITY_ERROR = "CHANGE_GROUP_VISIBILITY_ERROR";
export const CHANGE_GROUP_VISIBILITY_LOADING = "CHANGE_GROUP_VISIBILITY_LOADING";
export const CHANGE_GROUP_VISIBILITY_RESET = "CHANGE_GROUP_VISIBILITY_RESET";