export const SET_LOCATION_ACCURACY = "SET_LOCATION_ACCURACY";
export const GET_LOCATION_ACCURACY = "GET_LOCATION_ACCURACY";

export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const GET_USER_LOCATION = "GET_USER_LOCATION";
