export const GET_USER = "GET_USER";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_RESET = "GET_USER_RESET";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";
export const GET_ALL_USERS_LOADING = "GET_ALL_USERS_LOADING";
export const GET_ALL_USERS_RESET = "GET_ALL_USERS_RESET";

export const SEARCH_FRIENDS = "SEARCH_FRIENDS";
export const SEARCH_FRIENDS_ERROR = "SEARCH_FRIENDS_ERROR";
export const SEARCH_FRIENDS_LOADING = "SEARCH_FRIENDS_LOADING";
export const SEARCH_FRIENDS_RESET = "SEARCH_FRIENDS_RESET";

export const PROCESS_REQUEST = "PROCESS_REQUEST";
export const PROCESS_REQUEST_ERROR = "PROCESS_REQUEST_ERROR";
export const PROCESS_REQUEST_LOADING = "PROCESS_REQUEST_LOADING";
export const PROCESS_REQUEST_RESET = "PROCESS_REQUEST_RESET";

export const CHANGE_VISIBILITY = "CHANGE_VISIBILITY";
export const CHANGE_VISIBILITY_ERROR = "CHANGE_VISIBILITY_ERROR";
export const CHANGE_VISIBILITY_LOADING = "CHANGE_VISIBILITY_LOADING";
export const CHANGE_VISIBILITY_RESET = "CHANGE_VISIBILITY_RESET";

export const USER_REQUEST = "USER_REQUEST";
export const USER_REQUEST_ERROR = "USER_REQUEST_ERROR";
export const USER_REQUEST_LOADING = "USER_REQUEST_LOADING";
export const USER_REQUEST_RESET = "USER_REQUEST_RESET";

export const USER_PROFILE = "USER_PROFILE";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const GET_USER_BY_USER_NAME = "GET_USER_BY_USER_NAME";
export const GET_USER_BY_USER_NAME_ERROR = "GET_USER_BY_USER_NAME_ERROR";
export const GET_USER_BY_USER_NAME_LOADING = "GET_USER_BY_USER_NAME_LOADING";
export const GET_USER_BY_USER_NAME_RESET = "GET_USER_BY_USER_NAME_RESET";
