export const ADD_ANNOUNCEMENT = "ADD_ANNOUNCEMENT";
export const ADD_ANNOUNCEMENT_LOADING = "ADD_ANNOUNCEMENT_LOADING";
export const ADD_ANNOUNCEMENT_ERROR = "ADD_ANNOUNCEMENT_ERROR";
export const ADD_ANNOUNCEMENT_RESET = "ADD_ANNOUNCEMENT_RESET";

export const GET_ANNOUNCEMENTS = "GET_ANNOUNCEMENTS";
export const GET_ANNOUNCEMENTS_LOADING = "GET_ANNOUNCEMENTS_LOADING";
export const GET_ANNOUNCEMENTS_ERROR = "GET_ANNOUNCEMENTS_ERROR";
export const GET_ANNOUNCEMENTS_RESET = "GET_ANNOUNCEMENTS_RESET";
