export const GET_LOCATION_HISTORY = "GET_LOCATION_HISTORY";
export const GET_LOCATION_HISTORY_ERROR = "GET_LOCATION_HISTORY_ERROR";
export const GET_LOCATION_HISTORY_LOADING = "GET_LOCATION_HISTORY_LOADING";
export const GET_LOCATION_HISTORY_RESET = "GET_LOCATION_HISTORY_RESET";

export const SAVE_TRIP_HISTORY = "SAVE_TRIP_HISTORY";
export const SAVE_TRIP_HISTORY_ERROR = "SAVE_TRIP_HISTORY_ERROR";
export const SAVE_TRIP_HISTORY_LOADING = "SAVE_TRIP_HISTORY_LOADING";
export const SAVE_TRIP_HISTORY_RESET = "SAVE_TRIP_HISTORY_RESET";

export const GET_SAVE_TRIP_HISTORY = "GET_SAVE_TRIP_HISTORY";
export const GET_SAVE_TRIP_HISTORY_ERROR = "GET_SAVE_TRIP_HISTORY_ERROR";
export const GET_SAVE_TRIP_HISTORY_LOADING = "GET_SAVE_TRIP_HISTORY_LOADING";
export const GET_SAVE_TRIP_HISTORY_RESET = "GET_SAVE_TRIP_HISTORY_RESET";

export const DELETE_TRIP_HISTORY = "DELETE_TRIP_HISTORY";
export const DELETE_TRIP_HISTORY_ERROR = "DELETE_TRIP_HISTORY_ERROR";
export const DELETE_TRIP_HISTORY_LOADING = "DELETE_TRIP_HISTORY_LOADING";
export const DELETE_TRIP_HISTORY_RESET = "DELETE_TRIP_HISTORY_RESET";