export const GET_FRIENDS_LOCATION = "GET_FRIENDS_LOCATION";
export const GET_FRIENDS_LOCATION_ERROR = "GET_FRIENDS_LOCATION_ERROR";
export const GET_FRIENDS_LOCATION_LOADING = "GET_FRIENDS_LOCATION_LOADING";
export const GET_FRIENDS_LOCATION_RESET = "GET_FRIENDS_LOCATION_RESET";

export const SEND_LOCATION = "SEND_LOCATION";
export const SEND_LOCATION_RESET = "SEND_LOCATION_RESET";
export const SEND_LOCATION_ERROR = "SEND_LOCATION_ERROR";
export const SEND_LOCATION_LOADING = "SEND_LOCATION_LOADING";
