export const GET_FRIENDS = "GET_FRIENDS";
export const GET_FRIENDS_ERROR = "GET_FRIENDS_ERROR";
export const GET_FRIENDS_LOADING = "GET_FRIENDS_LOADING";
export const GET_FRIENDS_RESET = "GET_FRIENDS_RESET";
