export const SIGNUP_USER = "SIGNUP_USER";
export const LOADING_SIGNUP_USER = "LOADING_SIGNUP_USER";
export const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR";
export const SIGNUP_USER_RESET = "SIGNUP_USER_RESET";
